language: java

jdk:
  - oraclejdk8
  
sudo: required

services:
  - docker

script:
  - mvn -B install 
  - mvn -B verify -Pjetty-9-embedded-arquillian,coverage-per-test,arquillian-tests --projects session-replacement
  - mvn -B verify -Pwildfly-10-managed-arquillian,coverage-per-test,arquillian-tests --projects session-replacement
  - mvn -B verify -Ptomcat-7-embedded-arquillian,coverage-per-test,arquillian-tests --projects session-replacement

  - mvn -B verify -Ptest-instrumentation --projects integration-tests/agent-tests
  - mvn -B verify -Ptest-intercept-listeners --projects integration-tests/agent-tests

  - mvn -B verify -Pwildfly-10-managed-arquillian-with-agent,external-arquillian-tests --projects integration-tests/arquillian-tests
